### PR TITLE
Image build rework

### PR DESCRIPTION
**Pull request by wfg**
This change makes it simpler and more convenient to build the app.

If I should use a release branch as the base, please let me know, and I will rebase.

### CODE REVIEW

**Comment by svilenmarkov** [comment]
Hey, thanks for contributing!

**Comment by wfg** [comment]
@svilenmarkov I just realized this may break your build-and-ship script.

A proper build pipeline would be a good replacement for it anyway. If you'd like, I can work on that.

**Comment by svilenmarkov** [comment]
@wfg It shouldn't break the build script as it uses the other Dockerfile which wasn't changed by this PR, unless you have something else in mind? 

As for replacing it, potentially further down the line as I'm not yet ready to embrace the chaos of Makefiles, bash scripts and large Dockerfiles. Thank you for offering though!

**Comment by wfg** [comment]
>It shouldn't break the build script as it uses the other Dockerfile which wasn't changed by this PR, unless you have something else in mind?

I'm only thinking about the `.dockerignore` file not including the `/build/` directory referenced here: https://github.com/glanceapp/glance/blob/main/Dockerfile#L8
The quick-and-dirty answer is to add `!/build/` to `.dockerignore`.


>As for replacing it, potentially further down the line as I'm not yet ready to embrace the chaos of Makefiles, bash scripts and large Dockerfiles. Thank you for offering though!

I was going to make GitHub Actions do all that work for us :)
I'll play around with it on my fork and may submit a draft PR for you to take a peek at. I suspect it'll be a lot simpler than you're thinking.

Awesome project, by the way! I've been trying to find something like this and happened to come across it on Hacker News.

**Comment by svilenmarkov** [comment]
Ah right, yup, it does actually break it, nice catch.

If you do spend some time automating the build with GitHub Actions and it ends up being relatively straightforward while achieving much of the same then feel free to submit a PR and I'll have a look. Thanks again for offering help with this.

Also glad to hear you're finding it useful!

**Pull request merged**
